# Generated by Django 5.2.17 on 2026-08-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_address_payment_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='order_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
